import Vue from 'vue'
import { Ripple, Intersect, ClickOutside } from 'vuetify/lib/directives'
import Vuetify, {
  VAlert,
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VAutocomplete,
  VAvatar,
  VBadge,
  VBtn,
  VBtnToggle,
  VCalendar,
  VCard,
  VCardActions,
  VCardSubtitle,
  VCardText,
  VCardTitle,
  VCarousel,
  VCarouselItem,
  VCheckbox,
  VChip,
  VCol,
  VCombobox,
  VContainer,
  VDataTable,
  VDatePicker,
  VDialog,
  VDivider,
  VExpansionPanel,
  VExpansionPanelContent,
  VExpansionPanelHeader,
  VExpansionPanels,
  VFooter,
  VForm,
  VIcon,
  VImg,
  VLazy,
  VList,
  VListGroup,
  VListItem,
  VListItemAction,
  VListItemContent,
  VListItemIcon,
  VListItemTitle,
  VMain,
  VMenu,
  VNavigationDrawer,
  VOverlay,
  VProgressCircular,
  VRadio,
  VRadioGroup,
  VRow,
  VSelect,
  VSimpleCheckbox,
  VSimpleTable,
  VSkeletonLoader,
  VSnackbar,
  VSpacer,
  VSpeedDial,
  VStepper,
  VStepperHeader,
  VStepperStep,
  VSubheader,
  VSwitch,
  VTab,
  VTabs,
  VTextarea,
  VTextField,
  VToolbar,
  VToolbarTitle,
  VTooltip,
} from 'vuetify/lib'

import colors from 'vuetify/lib/util/colors'
import { DataTableHeader } from 'vuetify/types'

Vue.use(Vuetify, {
  components: {
    VAlert,
    VApp,
    VAppBar,
    VAppBarNavIcon,
    VAutocomplete,
    VAvatar,
    VBadge,
    VBtn,
    VBtnToggle,
    VCalendar,
    VCard,
    VCardActions,
    VCardSubtitle,
    VCardText,
    VCardTitle,
    VCarousel,
    VCarouselItem,
    VCheckbox,
    VChip,
    VCol,
    VCombobox,
    VContainer,
    VDataTable,
    VDatePicker,
    VDialog,
    VDivider,
    VExpansionPanel,
    VExpansionPanelContent,
    VExpansionPanelHeader,
    VExpansionPanels,
    VFooter,
    VForm,
    VIcon,
    VImg,
    VLazy,
    VList,
    VListGroup,
    VListItem,
    VListItemAction,
    VListItemContent,
    VListItemIcon,
    VListItemTitle,
    VMain,
    VMenu,
    VNavigationDrawer,
    VOverlay,
    VProgressCircular,
    VRadio,
    VRadioGroup,
    VRow,
    VSelect,
    VSimpleCheckbox,
    VSimpleTable,
    VSkeletonLoader,
    VSnackbar,
    VSpacer,
    VSpeedDial,
    VStepper,
    VStepperHeader,
    VStepperStep,
    VSubheader,
    VSwitch,
    VTab,
    VTabs,
    VTextarea,
    VTextField,
    VToolbar,
    VToolbarTitle,
    VTooltip,
  },
  directives: {
    Ripple,
    Intersect,
    ClickOutside,
  },
})

const lightThemeSettings = {
  primary: { ...colors.indigo },
  secondary: { ...colors.blue },
  accent: { ...colors.pink },
  neutral: { ...colors.grey },
  error: '#FF5252',
  info: '#2196F3',
  success: '#4CAF50',
  warning: '#FB8C00',
}

export type VFormObj = Vue & { validate(): boolean }
export type vDataTableHeader = DataTableHeader

export default new Vuetify({
  theme: {
    dark: false,
    themes: {
      light: lightThemeSettings,
    },
  },
  icons: {
    iconfont: 'mdi',
  },
})
